project:
  type: website
  output-dir: ..
  resources:
    - ../Figures/**
    - ../site_assets/**
    - ../dashboard.html
    - ../assets/**

website:
  title: "Philadelphia Healthcare Equity Explorer, Quarto Companion"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: methods.qmd
        text: Data and Methods
      - href: results.qmd
        text: Results
      - href: dashboard.qmd
        text: Dashboard
      - href: references.qmd
        text: References
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
